### ISSUE TITLE
VNC Server não inicia corretamente

### ISSUE THREAD

**Issue by davidalben** [allytiago/Ubuntu-no-Android#2]
O script rodou até o final, sem erros impeditivos. Porém, ao iniciar o VNC Server, depois de selecionar a resolução, ele apresenta as mensages abaixo (veja o Failed na última linha) e não inicia o ambiente. AVNC conecta, mas a tela fica preta.

```
Você escolheu a resolução Full HD resolution
Cleaning stale pidfile '/root/.vnc/localhost:5901.pid'!
Cleaning stale X11 lock '/tmp/.X1-lock'!
Cleaning stale X11 lock '/tmp/.X11-unix/X1'!

New Xtigervnc server 'remote-desktop' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /root/.vnc/passwd localhost:1 to connect to the VNC server.

Servidor VNC foi iniciado. A senha padrão é a senha da conta para root
Failed to init libxfconf: Failed to close file descriptor for child process (Invalid argument).
root@localhost:~#
```

Edit: Complementando, encontre este comentário em outra aplicação:

https://github.com/proot-me/proot/issues/357#issuecomment-1773382140

Poderia ser algo específico do Android 13.

**Comment by allytiago** [comment]
Notei que estava havendo esse problema nessas ultimas atualizações do repositório. Eu já estou tentando resolver. Pode usar o comando `vncpasswd` para reiniciar o comando de definir senha, depois encerrar o servidor com o comando `stopvnc` e reiniciar a vnc com o comando `startvnc`. Nos meus testes resolveram mas já estou analisando o caso para que não ocorra mais.

**Comment by allytiago** [comment]
A nova versão de instalação já corrige o script, mas caso não queira reinstalar o sistema novamente, pode usar o comando a baixo:

```shell
wget https://raw.githubusercontent.com/allytiago/Ubuntu-no-Android/main/config/xfce4/xfce4-config.sh && chmod +x xfce4-config.sh && bash xfce4-config.sh
```
O script irá atualizar os repositórios e reinstalar pacotes do xfce e solicitar a reconfiguração de senha. Mas recomendo fazer a reinstalação para a versão mais recente utilizando o [script de instalação principal](https://github.com/allytiago/Ubuntu-no-Android#passo-1---instalando-o-ubuntu).

**Comment by davidalben** [comment]
Oi, @allytiago . Fiz de duas formas:

1 - Simplesmente rodei o script novamente. Não funcionou.

2 - Apaguei os dados do Termux e rodei o script. Também não funcionou, mas o erro agora é outro:

```
Você escolheu a resolução Full HD resolution

New Xtigervnc server 'remote-desktop' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /root/.vnc/passwd localhost:1 to connect to the VNC server.

Servidor VNC foi iniciado. A senha padrão é a senha da conta para root
Failed to init libxfconf: Cannot autolaunch D-Bus without X11 $DISPLAY.
root@localhost:~#
```

**Comment by allytiago** [comment]
> Oi, @allytiago . Fiz de duas formas:
> 
> 1 - Simplesmente rodei o script novamente. Não funcionou.
> 
> 2 - Apaguei os dados do Termux e rodei o script. Também não funcionou, mas o erro agora é outro:
> 
> ```
> Você escolheu a resolução Full HD resolution
> 
> New Xtigervnc server 'remote-desktop' on port 5901 for display :1.
> Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /root/.vnc/passwd localhost:1 to connect to the VNC server.
> 
> Servidor VNC foi iniciado. A senha padrão é a senha da conta para root
> Failed to init libxfconf: Cannot autolaunch D-Bus without X11 $DISPLAY.
> root@localhost:~#
> ```



O script força a reconfiguração do sistema. 

Execute o comando`stopvnc` e depois o comando `vncpasswd` com o Ubuntu iniciado e depois envie uma print de como foi configurado o servidor no AVNC e outra do que aparece quando o tenta se conectar ao servidor pelo AVNC.

o script não auto inicia o AVNC, após executar o comando, deve abrir o app do AVNC e seguir os [passos para se conectar ao servidor e visualizar a interface](https://github.com/allytiago/Ubuntu-no-Android#passo-2---iniciando-a-interface-gráfica). 

O seu log do terminal apresenta um texto correto de instalação inicial. É comum aparecer o erro `Failed to init libxfconf: Cannot autolaunch D-Bus without X11 $DISPLAY.` devido algumas configurações aplicadas no instalador. Porém o erro só aparece uma única vez.

**Comment by allytiago** [comment]
Qual das 7 opções de resolução você está usando?

**Comment by davidalben** [comment]
@allytiago, o servidor VNC está iniciando com resolução FullHD (opção 4).

Quem não está iniciando é o X. Quando conecto com o AVNC, só recebo uma tela preta, por onde posso passear com o mouse, mas não tem absolutamente nada nela.

Já executei o start-ubuntu várias vezes e nada.

**Comment by allytiago** [comment]
Nesse caso, será necessário desinstalar sistema e reinstalar.

Para desinstalar use o comando:
```shell
pkg update -y && pkg install wget curl proot tar -y && wget https://raw.githubusercontent.com/allytiago/Ubuntu-no-Android/main/uninstall.sh -O ubuntu-uninstall.sh && chmod +x ubuntu-uninstall.sh && bash ubuntu-uninstall.sh
```

**Comment by allytiago** [comment]
> Arquitetura aarch64. Termux da F-Droid. Desinstalei, reinstalei e continua igual.
> 
> O VNC sobe (testei "errando" a senha e ele avisa que está errada) e o AVNC conecta. o XFCE sobe (se eu mandar iniciar novamente ele diz que já tem uma sessão rodando no display :1).
> 
> Fiquei com uma dúvida: no read.me você diz que a porta no AVNC tem que ser "1". No Andronix no S21 eu uso "5901". Mas tentei das duas formas e o resultado é o mesmo: uma tela preta. Tem alguma coisa errada com o XFCE, creio eu.

Poderia fazer uma gravação mostrando o passo a passo da instalação? Eu farei uma aqui para comparação.

**Comment by allytiago** [comment]
Acabei de identificar um problema nas configurações do AVNC. Troque a opção de Segurança para `Automático` ou para `VncAuth`.
>[!TIP]
>Recomendado a opção `VncAuth` para reduzir um pouco a latência.

**Comment by davidalben** [comment]
> Acabei de identificar um problema nas configurações do AVNC. Troque a opção de Segurança para `Automático` ou para `VncAuth`.
> 
> Tip
> 
> Recomendado a opção `VncAuth` para reduzir um pouco a latência.

Já fiz isso. Sem diferença.

**Comment by davidalben** [comment]
> Poderia fazer uma gravação mostrando o passo a passo da instalação? Eu farei uma aqui para comparação.

Tiago, a instalação neste tablet demora mais de 30 min. Não teria como fazer uma gravação.
